//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace market
{
    using System;
    using System.Collections.Generic;
    
    public partial class IslemOzet
    {
        public int Id { get; set; }
        public Nullable<int> dIslemNo { get; set; }
        public Nullable<bool> dIade { get; set; }
        public string dOdemeSekli { get; set; }
        public Nullable<double> dNakit { get; set; }
        public Nullable<double> dKart { get; set; }
        public Nullable<bool> dGelir { get; set; }
        public Nullable<bool> dGider { get; set; }
        public Nullable<double> dAlisFiyatToplam { get; set; }
        public string dAciklama { get; set; }
        public Nullable<System.DateTime> dTarih { get; set; }
        public string dKullanici { get; set; }
    }
}
