//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace market
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        public int Id { get; set; }
        public string dAdSoyad { get; set; }
        public string dTelefon { get; set; }
        public string dEposta { get; set; }
        public string dKullaniciAd { get; set; }
        public string dSifre { get; set; }
        public Nullable<bool> dSatis { get; set; }
        public Nullable<bool> dRapor { get; set; }
        public Nullable<bool> dStok { get; set; }
        public Nullable<bool> dUrunGiris { get; set; }
        public Nullable<bool> dAyarlar { get; set; }
        public Nullable<bool> dFiyatGuncelle { get; set; }
        public Nullable<bool> dYedekleme { get; set; }
    }
}
