//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace market
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satislar
    {
        public int SatisId { get; set; }
        public Nullable<int> dIslemNo { get; set; }
        public string dUrunAd { get; set; }
        public string dBarkod { get; set; }
        public string dUrunGrup { get; set; }
        public string dBirim { get; set; }
        public Nullable<double> dAlisFiyat { get; set; }
        public Nullable<double> dSatisFiyat { get; set; }
        public Nullable<double> dMikar { get; set; }
        public Nullable<double> dToplam { get; set; }
        public Nullable<double> dKdvTutari { get; set; }
        public string dOdemeSekli { get; set; }
        public Nullable<bool> dIade { get; set; }
        public Nullable<System.DateTime> dTarih { get; set; }
        public string dKullanici { get; set; }
    }
}
