//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace market
{
    using System;
    using System.Collections.Generic;
    
    public partial class StokHareket
    {
        public int Id { get; set; }
        public string dBarkod { get; set; }
        public string dUrunAd { get; set; }
        public string dBirim { get; set; }
        public Nullable<double> dMiktar { get; set; }
        public string dUrunGrup { get; set; }
        public string dKullanici { get; set; }
        public Nullable<System.DateTime> dTarih { get; set; }
    }
}
