//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace market
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veresiye
    {
        public int Id { get; set; }
        public string dAdSoyad { get; set; }
        public string dTelefon { get; set; }
        public Nullable<double> dMiktar { get; set; }
    }
}
