SET IDENTITY_INSERT [dbo].[HizliUrun] ON
INSERT INTO [dbo].[HizliUrun] ([Id], [dBarkod], [dUrunAd], [dFiyat]) VALUES (1, N'123456789', N'çiko', 2)
INSERT INTO [dbo].[HizliUrun] ([Id], [dBarkod], [dUrunAd], [dFiyat]) VALUES (2, N'-', N'-', 2)
INSERT INTO [dbo].[HizliUrun] ([Id], [dBarkod], [dUrunAd], [dFiyat]) VALUES (3, N'-', N'-', 2)
INSERT INTO [dbo].[HizliUrun] ([Id], [dBarkod], [dUrunAd], [dFiyat]) VALUES (4, N'-', N'-', 2)
INSERT INTO [dbo].[HizliUrun] ([Id], [dBarkod], [dUrunAd], [dFiyat]) VALUES (5, N'-', N'-', 3)
INSERT INTO [dbo].[HizliUrun] ([Id], [dBarkod], [dUrunAd], [dFiyat]) VALUES (6, N'-', N'-', 1)
INSERT INTO [dbo].[HizliUrun] ([Id], [dBarkod], [dUrunAd], [dFiyat]) VALUES (7, N'-', N'-', 2)
INSERT INTO [dbo].[HizliUrun] ([Id], [dBarkod], [dUrunAd], [dFiyat]) VALUES (8, N'-', N'-', 2)
INSERT INTO [dbo].[HizliUrun] ([Id], [dBarkod], [dUrunAd], [dFiyat]) VALUES (9, N'-', N'-', 2)
INSERT INTO [dbo].[HizliUrun] ([Id], [dBarkod], [dUrunAd], [dFiyat]) VALUES (10, N'-', N'-', 2)
INSERT INTO [dbo].[HizliUrun] ([Id], [dBarkod], [dUrunAd], [dFiyat]) VALUES (11, N'-', N'-', 2)
INSERT INTO [dbo].[HizliUrun] ([Id], [dBarkod], [dUrunAd], [dFiyat]) VALUES (12, N'-', N'-', 2)
INSERT INTO [dbo].[HizliUrun] ([Id], [dBarkod], [dUrunAd], [dFiyat]) VALUES (13, N'-', N'-', 2)
INSERT INTO [dbo].[HizliUrun] ([Id], [dBarkod], [dUrunAd], [dFiyat]) VALUES (14, N'-', N'-', 2)
INSERT INTO [dbo].[HizliUrun] ([Id], [dBarkod], [dUrunAd], [dFiyat]) VALUES (15, N'-', N'-', 2)
INSERT INTO [dbo].[HizliUrun] ([Id], [dBarkod], [dUrunAd], [dFiyat]) VALUES (16, N'-', N'-', 2)
INSERT INTO [dbo].[HizliUrun] ([Id], [dBarkod], [dUrunAd], [dFiyat]) VALUES (17, N'-', N'-', 2)
INSERT INTO [dbo].[HizliUrun] ([Id], [dBarkod], [dUrunAd], [dFiyat]) VALUES (18, N'-', N'-', 2)
INSERT INTO [dbo].[HizliUrun] ([Id], [dBarkod], [dUrunAd], [dFiyat]) VALUES (19, N'-', N'-', 2)
INSERT INTO [dbo].[HizliUrun] ([Id], [dBarkod], [dUrunAd], [dFiyat]) VALUES (20, N'-', N'-', 2)
INSERT INTO [dbo].[HizliUrun] ([Id], [dBarkod], [dUrunAd], [dFiyat]) VALUES (21, N'-', N'-', 2)
INSERT INTO [dbo].[HizliUrun] ([Id], [dBarkod], [dUrunAd], [dFiyat]) VALUES (22, N'-', N'-', 2)
INSERT INTO [dbo].[HizliUrun] ([Id], [dBarkod], [dUrunAd], [dFiyat]) VALUES (23, N'-', N'-', 2)
INSERT INTO [dbo].[HizliUrun] ([Id], [dBarkod], [dUrunAd], [dFiyat]) VALUES (24, N'-', N'-', 2)
INSERT INTO [dbo].[HizliUrun] ([Id], [dBarkod], [dUrunAd], [dFiyat]) VALUES (25, N'-', N'-', 2)
SET IDENTITY_INSERT [dbo].[HizliUrun] OFF
